service: qrcodes
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: staging
  region: eu-west-1

functions:
  putEventsLambda:
    handler: functions/putEvents.handler
    events:
      - http:
          path: /generate
          method: post

resources:
  Resources:
    ${file(./resources.yml)}
  Outputs:
    EventBusName:
      Value: !Ref QrEventBus
